// ============================================================================
// 
// <auto-generated>
// This code was generated by "CSV to resw".
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// 
// ============================================================================

using Microsoft.Windows.ApplicationModel.Resources;

namespace CsvToReswSample.Strings;

internal enum Localize
{
	AppInfo_AppName,
	AppInfo_Description,
	MainPageViewModel_MessageTitle,
	MainPageViewModel_MessageContent,
	MainPageViewModel_ButtonOk,

}

internal static class LocalizeExtensions
{
	/// <summary>
	/// Returns the most appropriate string value of a resource
	/// </summary>
	/// <param name="localizeKey">Localize enum</param>
	/// <returns></returns>
	public static String Localized(this Localize localizeKey)
	{
		return _resourceLoader.GetString(localizeKey.ToString());
	}

	/// <summary>
	/// ResourceLoader
	/// </summary>
	private static readonly ResourceLoader _resourceLoader = new();
}



